
 Network hfurlan-java-v1_rinha-net  Creating
 Network hfurlan-java-v1_rinha-net  Created
 Container hfurlan-java-v1-db-1  Creating
 Container hfurlan-java-v1-db-1  Created
 Container hfurlan-java-v1-api02-1  Creating
 Container hfurlan-java-v1-api01-1  Creating
 Container hfurlan-java-v1-api02-1  Created
 Container hfurlan-java-v1-api01-1  Created
 Container hfurlan-java-v1-lb-1  Creating
 Container hfurlan-java-v1-lb-1  Created
Attaching to api01-1, api02-1, db-1, lb-1
db-1  | The files belonging to this database system will be owned by user "postgres".
db-1  | This user must also own the server process.
db-1  | 
db-1  | The database cluster will be initialized with locale "en_US.utf8".
db-1  | The default database encoding has accordingly been set to "UTF8".
db-1  | The default text search configuration will be set to "english".
db-1  | 
db-1  | Data page checksums are disabled.
db-1  | 
db-1  | fixing permissions on existing directory /var/lib/postgresql/data ... ok
db-1  | creating subdirectories ... ok
db-1  | selecting dynamic shared memory implementation ... posix
db-1  | selecting default max_connections ... 100
db-1  | selecting default shared_buffers ... 128MB
db-1  | selecting default time zone ... UTC
db-1  | creating configuration files ... ok
db-1  | running bootstrap script ... ok
db-1  | sh: locale: not found
db-1  | 2025-08-18 20:11:11.997 UTC [35] WARNING:  no usable system locales were found
db-1  | performing post-bootstrap initialization ... ok
db-1  | syncing data to disk ... ok
db-1  | 
db-1  | 
db-1  | Success. You can now start the database server using:
db-1  | 
db-1  |     pg_ctl -D /var/lib/postgresql/data -l logfile start
db-1  | 
db-1  | initdb: warning: enabling "trust" authentication for local connections
db-1  | initdb: hint: You can change this by editing pg_hba.conf or using the option -A, or --auth-local and --auth-host, the next time you run initdb.
db-1  | waiting for server to start....2025-08-18 20:11:13.358 UTC [41] LOG:  starting PostgreSQL 16.9 on x86_64-pc-linux-musl, compiled by gcc (Alpine 14.2.0) 14.2.0, 64-bit
db-1  | 2025-08-18 20:11:13.358 UTC [41] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
db-1  | 2025-08-18 20:11:13.360 UTC [44] LOG:  database system was shut down at 2025-08-18 20:11:13 UTC
db-1  | 2025-08-18 20:11:13.364 UTC [41] LOG:  database system is ready to accept connections
db-1  |  done
db-1  | server started
db-1  | CREATE DATABASE
db-1  | 
db-1  | 
db-1  | /usr/local/bin/docker-entrypoint.sh: running /docker-entrypoint-initdb.d/ddl.sql
db-1  | CREATE TABLE
db-1  | CREATE INDEX
db-1  | CREATE TABLE
db-1  | CREATE TABLE
db-1  | 
db-1  | 
db-1  | /usr/local/bin/docker-entrypoint.sh: running /docker-entrypoint-initdb.d/dml.sql
db-1  | INSERT 0 1
db-1  | 
db-1  | 
db-1  | waiting for server to shut down...2025-08-18 20:11:13.656 UTC [41] LOG:  received fast shutdown request
db-1  | .2025-08-18 20:11:13.656 UTC [41] LOG:  aborting any active transactions
db-1  | 2025-08-18 20:11:13.659 UTC [41] LOG:  background worker "logical replication launcher" (PID 47) exited with exit code 1
db-1  | 2025-08-18 20:11:13.660 UTC [42] LOG:  shutting down
db-1  | 2025-08-18 20:11:13.660 UTC [42] LOG:  checkpoint starting: shutdown immediate
db-1  | 2025-08-18 20:11:13.669 UTC [42] LOG:  checkpoint complete: wrote 935 buffers (22.8%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.009 s, sync=0.001 s, total=0.010 s; sync files=0, longest=0.000 s, average=0.000 s; distance=4313 kB, estimate=4313 kB; lsn=0/1928B18, redo lsn=0/1928B18
db-1  | 2025-08-18 20:11:13.750 UTC [41] LOG:  database system is shut down
db-1  |  done
db-1  | server stopped
db-1  | 
db-1  | PostgreSQL init process complete; ready for start up.
db-1  | 
db-1  | 2025-08-18 20:11:13.772 UTC [1] LOG:  starting PostgreSQL 16.9 on x86_64-pc-linux-musl, compiled by gcc (Alpine 14.2.0) 14.2.0, 64-bit
db-1  | 2025-08-18 20:11:13.772 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
db-1  | 2025-08-18 20:11:13.772 UTC [1] LOG:  listening on IPv6 address "::", port 5432
db-1  | 2025-08-18 20:11:13.772 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
db-1  | 2025-08-18 20:11:13.775 UTC [61] LOG:  database system was shut down at 2025-08-18 20:11:13 UTC
db-1  | 2025-08-18 20:11:13.779 UTC [1] LOG:  database system is ready to accept connections
lb-1  | /docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
lb-1  | /docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
lb-1  | /docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
lb-1  | 10-listen-on-ipv6-by-default.sh: info: Getting the checksum of /etc/nginx/conf.d/default.conf
lb-1  | 10-listen-on-ipv6-by-default.sh: info: Enabled listen on IPv6 in /etc/nginx/conf.d/default.conf
lb-1  | /docker-entrypoint.sh: Sourcing /docker-entrypoint.d/15-local-resolvers.envsh
lb-1  | /docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
lb-1  | /docker-entrypoint.sh: Launching /docker-entrypoint.d/30-tune-worker-processes.sh
lb-1  | /docker-entrypoint.sh: Configuration complete; ready for start up
lb-1  | 2025/08/18 20:11:19 [error] 29#29: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: , request: "GET /payments-summary HTTP/1.1", upstream: "http://172.21.0.3:8080/payments-summary", host: "localhost:9999"
lb-1  | 2025/08/18 20:11:19 [error] 29#29: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: , request: "GET /payments-summary HTTP/1.1", upstream: "http://172.21.0.4:8080/payments-summary", host: "localhost:9999"
api02-1  | 
api02-1  |   .   ____          _            __ _ _
api02-1  |  /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
api02-1  | ( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
api02-1  |  \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
api02-1  |   '  |____| .__|_| |_|_| |_\__, | / / / /
api02-1  |  =========|_|==============|___/=/_/_/_/
api02-1  | 
api02-1  |  :: Spring Boot ::                (v3.5.4)
api02-1  | 
lb-1     | 2025/08/18 20:11:24 [error] 29#29: *4 no live upstreams while connecting to upstream, client: 172.21.0.1, server: , request: "GET /payments-summary HTTP/1.1", upstream: "http://api/payments-summary", host: "localhost:9999"
api01-1  | 
api01-1  |   .   ____          _            __ _ _
api01-1  |  /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
api01-1  | ( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
api01-1  |  \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
api01-1  |   '  |____| .__|_| |_|_| |_\__, | / / / /
api01-1  |  =========|_|==============|___/=/_/_/_/
api01-1  | 
lb-1     | 2025/08/18 20:11:29 [error] 29#29: *5 no live upstreams while connecting to upstream, client: 172.21.0.1, server: , request: "GET /payments-summary HTTP/1.1", upstream: "http://api/payments-summary", host: "localhost:9999"
api01-1  |  :: Spring Boot ::                (v3.5.4)
api01-1  | 
lb-1     | 2025/08/18 20:11:34 [error] 29#29: *6 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: , request: "GET /payments-summary HTTP/1.1", upstream: "http://172.21.0.4:8080/payments-summary", host: "localhost:9999"
lb-1     | 2025/08/18 20:11:34 [error] 29#29: *6 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: , request: "GET /payments-summary HTTP/1.1", upstream: "http://172.21.0.3:8080/payments-summary", host: "localhost:9999"
lb-1     | 2025/08/18 20:11:39 [error] 29#29: *9 no live upstreams while connecting to upstream, client: 172.21.0.1, server: , request: "GET /payments-summary HTTP/1.1", upstream: "http://api/payments-summary", host: "localhost:9999"
lb-1     | 2025/08/18 20:11:44 [error] 29#29: *10 no live upstreams while connecting to upstream, client: 172.21.0.1, server: , request: "GET /payments-summary HTTP/1.1", upstream: "http://api/payments-summary", host: "localhost:9999"
[Kapi02-1 exited with code 137
lb-1     | 2025/08/18 20:12:05 [error] 29#29: *15 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: , request: "GET /payments-summary HTTP/1.1", upstream: "http://172.21.0.3:8080/payments-summary", host: "localhost:9999"
lb-1     | 2025/08/18 20:12:37 [error] 29#29: *24 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: , request: "GET /payments-summary HTTP/1.1", upstream: "http://172.21.0.3:8080/payments-summary", host: "localhost:9999"
[Klb-1 exited with code 0
[Kapi01-1 exited with code 137
db-1     | 2025-08-18 20:12:56.860 UTC [1] LOG:  received fast shutdown request
db-1     | 2025-08-18 20:12:56.860 UTC [1] LOG:  aborting any active transactions
db-1     | 2025-08-18 20:12:56.863 UTC [1] LOG:  background worker "logical replication launcher" (PID 64) exited with exit code 1
db-1     | 2025-08-18 20:12:56.864 UTC [59] LOG:  shutting down
db-1     | 2025-08-18 20:12:56.865 UTC [59] LOG:  checkpoint starting: shutdown immediate
db-1     | 2025-08-18 20:12:56.866 UTC [59] LOG:  checkpoint complete: wrote 35 buffers (0.9%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.001 s, sync=0.001 s, total=0.001 s; sync files=0, longest=0.000 s, average=0.000 s; distance=139 kB, estimate=139 kB; lsn=0/194BAB8, redo lsn=0/194BAB8
db-1     | 2025-08-18 20:12:56.870 UTC [1] LOG:  database system is shut down
