
 Network alcides-e-antonio_backend  Creating
 Network alcides-e-antonio_backend  Created
 Container alcides-e-antonio-db-1  Creating
 Container alcides-e-antonio-db-1  Created
 Container alcides-e-antonio-api02-1  Creating
 Container alcides-e-antonio-api01-1  Creating
 Container alcides-e-antonio-api02-1  Created
 Container alcides-e-antonio-api01-1  Created
 Container alcides-e-antonio-elb-1  Creating
 Container alcides-e-antonio-elb-1  Created
Attaching to api01-1, api02-1, db-1, elb-1
db-1  | The files belonging to this database system will be owned by user "postgres".
db-1  | This user must also own the server process.
db-1  | 
db-1  | The database cluster will be initialized with locale "en_US.utf8".
db-1  | The default database encoding has accordingly been set to "UTF8".
db-1  | The default text search configuration will be set to "english".
db-1  | 
db-1  | Data page checksums are disabled.
db-1  | 
db-1  | fixing permissions on existing directory /var/lib/postgresql/data ... ok
db-1  | creating subdirectories ... ok
db-1  | selecting dynamic shared memory implementation ... posix
db-1  | selecting default max_connections ... 100
db-1  | selecting default shared_buffers ... 128MB
db-1  | selecting default time zone ... Etc/UTC
api02-1  | Picked up JAVA_TOOL_OPTIONS: -Xms120m -Xmx120m
api01-1  | Picked up JAVA_TOOL_OPTIONS: -Xms120m -Xmx120m
db-1     | creating configuration files ... ok
db-1     | running bootstrap script ... ok
elb-1    | [NOTICE]   (1) : Initializing new worker (8)
elb-1    | [NOTICE]   (1) : Loading success.
api02-1  | 2025-08-18 06:24:01.400 [main] DEBUG i.v.c.internal.logging.LoggerFactory - Using io.vertx.core.logging.SLF4JLogDelegateFactory
api01-1  | 2025-08-18 06:24:01.490 [main] DEBUG i.v.c.internal.logging.LoggerFactory - Using io.vertx.core.logging.SLF4JLogDelegateFactory
api02-1  | 2025-08-18 06:24:02.106 [main] DEBUG i.n.u.i.l.InternalLoggerFactory - Using SLF4J as the default logging framework
api02-1  | 2025-08-18 06:24:02.109 [main] DEBUG i.n.util.internal.PlatformDependent0 - Java version: 21
api02-1  | 2025-08-18 06:24:02.109 [main] DEBUG i.n.util.internal.PlatformDependent0 - -Dio.netty.noUnsafe: false
api02-1  | 2025-08-18 06:24:02.113 [main] DEBUG i.n.util.internal.PlatformDependent0 - sun.misc.Unsafe.theUnsafe: available
api02-1  | 2025-08-18 06:24:02.114 [main] DEBUG i.n.util.internal.PlatformDependent0 - sun.misc.Unsafe base methods: all available
api02-1  | 2025-08-18 06:24:02.115 [main] DEBUG i.n.util.internal.PlatformDependent0 - java.nio.Buffer.address: available
api02-1  | 2025-08-18 06:24:02.115 [main] DEBUG i.n.util.internal.PlatformDependent0 - direct buffer constructor: unavailable: Reflective setAccessible(true) disabled
api02-1  | 2025-08-18 06:24:02.116 [main] DEBUG i.n.util.internal.PlatformDependent0 - java.nio.Bits.unaligned: available, true
api01-1  | 2025-08-18 06:24:02.190 [main] DEBUG i.n.u.i.l.InternalLoggerFactory - Using SLF4J as the default logging framework
api02-1  | 2025-08-18 06:24:02.116 [main] DEBUG i.n.util.internal.PlatformDependent0 - jdk.internal.misc.Unsafe.allocateUninitializedArray(int): unavailable: symbolic reference class is not accessible: class jdk.internal.misc.Unsafe, from class io.netty.util.internal.PlatformDependent0 (unnamed module @238d7bbb)
api02-1  | 2025-08-18 06:24:02.191 [main] DEBUG i.n.util.internal.PlatformDependent0 - java.nio.DirectByteBuffer.<init>(long, {int,long}): unavailable
api02-1  | 2025-08-18 06:24:02.191 [main] DEBUG i.n.util.internal.PlatformDependent - sun.misc.Unsafe: available
api02-1  | 2025-08-18 06:24:02.192 [main] DEBUG i.n.util.internal.PlatformDependent - -Dio.netty.tmpdir: /tmp (java.io.tmpdir)
api02-1  | 2025-08-18 06:24:02.192 [main] DEBUG i.n.util.internal.PlatformDependent - -Dio.netty.bitMode: 64 (sun.arch.data.model)
api02-1  | 2025-08-18 06:24:02.192 [main] DEBUG i.n.util.internal.PlatformDependent - -Dio.netty.maxDirectMemory: -1 bytes
api01-1  | 2025-08-18 06:24:02.192 [main] DEBUG i.n.util.internal.PlatformDependent0 - Java version: 21
api01-1  | 2025-08-18 06:24:02.192 [main] DEBUG i.n.util.internal.PlatformDependent0 - -Dio.netty.noUnsafe: false
api01-1  | 2025-08-18 06:24:02.194 [main] DEBUG i.n.util.internal.PlatformDependent0 - sun.misc.Unsafe.theUnsafe: available
api02-1  | 2025-08-18 06:24:02.195 [main] DEBUG io.netty.util.internal.CleanerJava9 - java.nio.ByteBuffer.cleaner(): available
api02-1  | 2025-08-18 06:24:02.195 [main] DEBUG i.n.util.internal.PlatformDependent - -Dio.netty.noPreferDirect: false
api01-1  | 2025-08-18 06:24:02.195 [main] DEBUG i.n.util.internal.PlatformDependent0 - sun.misc.Unsafe base methods: all available
api01-1  | 2025-08-18 06:24:02.196 [main] DEBUG i.n.util.internal.PlatformDependent0 - java.nio.Buffer.address: available
api01-1  | 2025-08-18 06:24:02.197 [main] DEBUG i.n.util.internal.PlatformDependent0 - direct buffer constructor: unavailable: Reflective setAccessible(true) disabled
api01-1  | 2025-08-18 06:24:02.197 [main] DEBUG i.n.util.internal.PlatformDependent0 - java.nio.Bits.unaligned: available, true
api01-1  | 2025-08-18 06:24:02.198 [main] DEBUG i.n.util.internal.PlatformDependent0 - jdk.internal.misc.Unsafe.allocateUninitializedArray(int): unavailable: symbolic reference class is not accessible: class jdk.internal.misc.Unsafe, from class io.netty.util.internal.PlatformDependent0 (unnamed module @238d7bbb)
api01-1  | 2025-08-18 06:24:02.198 [main] DEBUG i.n.util.internal.PlatformDependent0 - java.nio.DirectByteBuffer.<init>(long, {int,long}): unavailable
api01-1  | 2025-08-18 06:24:02.198 [main] DEBUG i.n.util.internal.PlatformDependent - sun.misc.Unsafe: available
api01-1  | 2025-08-18 06:24:02.198 [main] DEBUG i.n.util.internal.PlatformDependent - -Dio.netty.tmpdir: /tmp (java.io.tmpdir)
api01-1  | 2025-08-18 06:24:02.198 [main] DEBUG i.n.util.internal.PlatformDependent - -Dio.netty.bitMode: 64 (sun.arch.data.model)
api01-1  | 2025-08-18 06:24:02.199 [main] DEBUG i.n.util.internal.PlatformDependent - -Dio.netty.maxDirectMemory: -1 bytes
api01-1  | 2025-08-18 06:24:02.201 [main] DEBUG io.netty.util.internal.CleanerJava9 - java.nio.ByteBuffer.cleaner(): available
api01-1  | 2025-08-18 06:24:02.201 [main] DEBUG i.n.util.internal.PlatformDependent - -Dio.netty.noPreferDirect: false
api02-1  | 2025-08-18 06:24:02.623 [main] DEBUG io.netty.util.ResourceLeakDetector - -Dio.netty.leakDetection.level: simple
api02-1  | 2025-08-18 06:24:02.623 [main] DEBUG io.netty.util.ResourceLeakDetector - -Dio.netty.leakDetection.targetRecords: 4
api01-1  | 2025-08-18 06:24:02.623 [main] DEBUG io.netty.util.ResourceLeakDetector - -Dio.netty.leakDetection.level: simple
api01-1  | 2025-08-18 06:24:02.683 [main] DEBUG io.netty.util.ResourceLeakDetector - -Dio.netty.leakDetection.targetRecords: 4
api01-1  | 2025-08-18 06:24:02.710 [main] DEBUG i.n.c.MultithreadEventLoopGroup - -Dio.netty.eventLoopThreads: 8
api02-1  | 2025-08-18 06:24:02.710 [main] DEBUG i.n.c.MultithreadEventLoopGroup - -Dio.netty.eventLoopThreads: 8
api02-1  | 2025-08-18 06:24:02.714 [main] DEBUG io.netty.channel.nio.NioIoHandler - -Dio.netty.noKeySetOptimization: false
api02-1  | 2025-08-18 06:24:02.714 [main] DEBUG io.netty.channel.nio.NioIoHandler - -Dio.netty.selectorAutoRebuildThreshold: 512
db-1     | performing post-bootstrap initialization ... ok
api01-1  | 2025-08-18 06:24:02.784 [main] DEBUG io.netty.channel.nio.NioIoHandler - -Dio.netty.noKeySetOptimization: false
api01-1  | 2025-08-18 06:24:02.784 [main] DEBUG io.netty.channel.nio.NioIoHandler - -Dio.netty.selectorAutoRebuildThreshold: 512
db-1     | initdb: warning: enabling "trust" authentication for local connections
db-1     | initdb: hint: You can change this by editing pg_hba.conf or using the option -A, or --auth-local and --auth-host, the next time you run initdb.
db-1     | syncing data to disk ... ok
db-1     | 
db-1     | 
db-1     | Success. You can now start the database server using:
db-1     | 
db-1     |     pg_ctl -D /var/lib/postgresql/data -l logfile start
db-1     | 
api01-1  | 2025-08-18 06:24:02.791 [main] DEBUG i.n.u.concurrent.GlobalEventExecutor - -Dio.netty.globalEventExecutor.quietPeriodSeconds: 1
api02-1  | 2025-08-18 06:24:02.794 [main] DEBUG i.n.u.concurrent.GlobalEventExecutor - -Dio.netty.globalEventExecutor.quietPeriodSeconds: 1
api02-1  | 2025-08-18 06:24:02.801 [main] DEBUG i.n.u.i.InternalThreadLocalMap - -Dio.netty.threadLocalMap.stringBuilder.initialSize: 1024
api02-1  | 2025-08-18 06:24:02.801 [main] DEBUG i.n.u.i.InternalThreadLocalMap - -Dio.netty.threadLocalMap.stringBuilder.maxSize: 4096
api01-1  | 2025-08-18 06:24:02.801 [main] DEBUG i.n.u.i.InternalThreadLocalMap - -Dio.netty.threadLocalMap.stringBuilder.initialSize: 1024
api01-1  | 2025-08-18 06:24:02.801 [main] DEBUG i.n.u.i.InternalThreadLocalMap - -Dio.netty.threadLocalMap.stringBuilder.maxSize: 4096
db-1     | waiting for server to start....2025-08-18 06:24:02.852 UTC [48] LOG:  starting PostgreSQL 16.9 (Debian 16.9-1.pgdg130+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 14.2.0-19) 14.2.0, 64-bit
db-1     | 2025-08-18 06:24:02.853 UTC [48] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
db-1     | 2025-08-18 06:24:02.855 UTC [51] LOG:  database system was shut down at 2025-08-18 06:24:02 UTC
db-1     | 2025-08-18 06:24:02.859 UTC [48] LOG:  database system is ready to accept connections
api01-1  | 2025-08-18 06:24:02.889 [main] DEBUG i.n.r.d.DefaultDnsServerAddressStreamProvider - Default DNS servers: [/127.0.0.11:53] (sun.net.dns.ResolverConfiguration)
api02-1  | 2025-08-18 06:24:02.893 [main] DEBUG i.n.r.d.DefaultDnsServerAddressStreamProvider - Default DNS servers: [/127.0.0.11:53] (sun.net.dns.ResolverConfiguration)
api02-1  | 2025-08-18 06:24:02.911 [main] DEBUG io.netty.util.NetUtil - -Djava.net.preferIPv4Stack: false
api02-1  | 2025-08-18 06:24:02.911 [main] DEBUG io.netty.util.NetUtil - -Djava.net.preferIPv6Addresses: false
api02-1  | 2025-08-18 06:24:02.913 [main] DEBUG i.netty.util.NetUtilInitializations - Loopback interface: lo (lo, 0:0:0:0:0:0:0:1%lo)
db-1     |  done
db-1     | server started
api01-1  | 2025-08-18 06:24:02.985 [main] DEBUG io.netty.util.NetUtil - -Djava.net.preferIPv4Stack: false
api01-1  | 2025-08-18 06:24:02.985 [main] DEBUG io.netty.util.NetUtil - -Djava.net.preferIPv6Addresses: false
api01-1  | 2025-08-18 06:24:02.987 [main] DEBUG i.netty.util.NetUtilInitializations - Loopback interface: lo (lo, 0:0:0:0:0:0:0:1%lo)
api01-1  | 2025-08-18 06:24:02.988 [main] DEBUG io.netty.util.NetUtil - /proc/sys/net/core/somaxconn: 4096
api01-1  | 2025-08-18 06:24:02.988 [main] DEBUG i.netty.resolver.dns.DnsNameResolver - Default ResolvedAddressTypes: IPV4_ONLY
api01-1  | 2025-08-18 06:24:02.989 [main] DEBUG i.netty.resolver.dns.DnsNameResolver - Localhost address: localhost/127.0.0.1
api01-1  | 2025-08-18 06:24:02.989 [main] DEBUG i.netty.resolver.dns.DnsNameResolver - Windows hostname: null
api02-1  | 2025-08-18 06:24:02.991 [main] DEBUG io.netty.util.NetUtil - /proc/sys/net/core/somaxconn: 4096
api02-1  | 2025-08-18 06:24:02.992 [main] DEBUG i.netty.resolver.dns.DnsNameResolver - Default ResolvedAddressTypes: IPV4_ONLY
api02-1  | 2025-08-18 06:24:02.993 [main] DEBUG i.netty.resolver.dns.DnsNameResolver - Localhost address: localhost/127.0.0.1
api02-1  | 2025-08-18 06:24:02.993 [main] DEBUG i.netty.resolver.dns.DnsNameResolver - Windows hostname: null
api01-1  | 2025-08-18 06:24:02.998 [main] DEBUG i.netty.resolver.dns.DnsNameResolver - Default search domains: [ec2.internal]
api02-1  | 2025-08-18 06:24:02.998 [main] DEBUG i.netty.resolver.dns.DnsNameResolver - Default search domains: [ec2.internal]
api01-1  | 2025-08-18 06:24:02.999 [main] DEBUG i.netty.resolver.dns.DnsNameResolver - Default UnixResolverOptions{ndots=0, timeout=5, attempts=16}
api02-1  | 2025-08-18 06:24:02.999 [main] DEBUG i.netty.resolver.dns.DnsNameResolver - Default UnixResolverOptions{ndots=0, timeout=5, attempts=16}
api02-1  | 2025-08-18 06:24:03.012 [main] DEBUG i.n.r.DefaultHostsFileEntriesResolver - -Dio.netty.hostsFileRefreshInterval: 0
api01-1  | 2025-08-18 06:24:03.012 [main] DEBUG i.n.r.DefaultHostsFileEntriesResolver - -Dio.netty.hostsFileRefreshInterval: 0
db-1     | CREATE DATABASE
db-1     | 
db-1     | 
db-1     | /usr/local/bin/docker-entrypoint.sh: running /docker-entrypoint-initdb.d/init.sql
db-1     | CREATE TABLE
db-1     | 
db-1     | 
db-1     | waiting for server to shut down...2025-08-18 06:24:03.237 UTC [48] LOG:  received fast shutdown request
db-1     | .2025-08-18 06:24:03.237 UTC [48] LOG:  aborting any active transactions
db-1     | 2025-08-18 06:24:03.239 UTC [48] LOG:  background worker "logical replication launcher" (PID 54) exited with exit code 1
db-1     | 2025-08-18 06:24:03.240 UTC [49] LOG:  shutting down
db-1     | 2025-08-18 06:24:03.240 UTC [49] LOG:  checkpoint starting: shutdown immediate
db-1     | 2025-08-18 06:24:03.249 UTC [49] LOG:  checkpoint complete: wrote 926 buffers (5.7%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.010 s, sync=0.001 s, total=0.010 s; sync files=0, longest=0.000 s, average=0.000 s; distance=4280 kB, estimate=4280 kB; lsn=0/1920D18, redo lsn=0/1920D18
api01-1  | 2025-08-18 06:24:03.300 [vert.x-eventloop-thread-1] DEBUG i.n.util.internal.PlatformDependent - org.jctools-core.MpscChunkedArrayQueue: available
api02-1  | 2025-08-18 06:24:03.300 [vert.x-eventloop-thread-1] DEBUG i.n.util.internal.PlatformDependent - org.jctools-core.MpscChunkedArrayQueue: available
db-1     | 2025-08-18 06:24:03.317 UTC [48] LOG:  database system is shut down
db-1     |  done
db-1     | server stopped
db-1     | 
db-1     | PostgreSQL init process complete; ready for start up.
db-1     | 
db-1     | 2025-08-18 06:24:03.360 UTC [1] LOG:  starting PostgreSQL 16.9 (Debian 16.9-1.pgdg130+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 14.2.0-19) 14.2.0, 64-bit
db-1     | 2025-08-18 06:24:03.361 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
db-1     | 2025-08-18 06:24:03.361 UTC [1] LOG:  listening on IPv6 address "::", port 5432
db-1     | 2025-08-18 06:24:03.361 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
db-1     | 2025-08-18 06:24:03.363 UTC [66] LOG:  database system was shut down at 2025-08-18 06:24:03 UTC
db-1     | 2025-08-18 06:24:03.368 UTC [1] LOG:  database system is ready to accept connections
api02-1  | 2025-08-18 06:24:03.715 [vert.x-eventloop-thread-1] DEBUG i.n.buffer.AdaptiveByteBufAllocator - -Dio.netty.allocator.useCachedMagazinesForNonEventLoopThreads: false
api02-1  | 2025-08-18 06:24:03.726 [vert.x-eventloop-thread-1] DEBUG io.netty.util.Recycler - -Dio.netty.recycler.maxCapacityPerThread: 4096
api02-1  | 2025-08-18 06:24:03.726 [vert.x-eventloop-thread-1] DEBUG io.netty.util.Recycler - -Dio.netty.recycler.ratio: 8
api02-1  | 2025-08-18 06:24:03.726 [vert.x-eventloop-thread-1] DEBUG io.netty.util.Recycler - -Dio.netty.recycler.chunkSize: 32
api02-1  | 2025-08-18 06:24:03.726 [vert.x-eventloop-thread-1] DEBUG io.netty.util.Recycler - -Dio.netty.recycler.blocking: false
api02-1  | 2025-08-18 06:24:03.726 [vert.x-eventloop-thread-1] DEBUG io.netty.util.Recycler - -Dio.netty.recycler.batchFastThreadLocalOnly: true
api01-1  | 2025-08-18 06:24:03.789 [vert.x-eventloop-thread-1] DEBUG i.n.buffer.AdaptiveByteBufAllocator - -Dio.netty.allocator.useCachedMagazinesForNonEventLoopThreads: false
api02-1  | 2025-08-18 06:24:03.793 [vert.x-eventloop-thread-1] DEBUG io.netty.buffer.ByteBufUtil - -Dio.netty.allocator.type: adaptive
api02-1  | 2025-08-18 06:24:03.793 [vert.x-eventloop-thread-1] DEBUG io.netty.buffer.ByteBufUtil - -Dio.netty.threadLocalDirectBufferSize: 0
api02-1  | 2025-08-18 06:24:03.793 [vert.x-eventloop-thread-1] DEBUG io.netty.buffer.ByteBufUtil - -Dio.netty.maxThreadLocalCharBufferSize: 16384
api01-1  | 2025-08-18 06:24:03.884 [vert.x-eventloop-thread-1] DEBUG io.netty.util.Recycler - -Dio.netty.recycler.maxCapacityPerThread: 4096
api01-1  | 2025-08-18 06:24:03.884 [vert.x-eventloop-thread-1] DEBUG io.netty.util.Recycler - -Dio.netty.recycler.ratio: 8
api01-1  | 2025-08-18 06:24:03.884 [vert.x-eventloop-thread-1] DEBUG io.netty.util.Recycler - -Dio.netty.recycler.chunkSize: 32
api01-1  | 2025-08-18 06:24:03.885 [vert.x-eventloop-thread-1] DEBUG io.netty.util.Recycler - -Dio.netty.recycler.blocking: false
api01-1  | 2025-08-18 06:24:03.885 [vert.x-eventloop-thread-1] DEBUG io.netty.util.Recycler - -Dio.netty.recycler.batchFastThreadLocalOnly: true
api01-1  | 2025-08-18 06:24:03.887 [vert.x-eventloop-thread-1] DEBUG io.netty.buffer.ByteBufUtil - -Dio.netty.allocator.type: adaptive
api01-1  | 2025-08-18 06:24:03.887 [vert.x-eventloop-thread-1] DEBUG io.netty.buffer.ByteBufUtil - -Dio.netty.threadLocalDirectBufferSize: 0
api01-1  | 2025-08-18 06:24:03.887 [vert.x-eventloop-thread-1] DEBUG io.netty.buffer.ByteBufUtil - -Dio.netty.maxThreadLocalCharBufferSize: 16384
api02-1  | 2025-08-18 06:24:03.894 [vert.x-eventloop-thread-1] DEBUG io.netty.channel.DefaultChannelId - -Dio.netty.processId: 1 (auto-detected)
api02-1  | 2025-08-18 06:24:03.896 [vert.x-eventloop-thread-1] DEBUG io.netty.channel.DefaultChannelId - -Dio.netty.machineId: 0e:92:8f:ff:fe:8e:97:35 (auto-detected)
api01-1  | 2025-08-18 06:24:03.903 [vert.x-eventloop-thread-1] DEBUG io.netty.channel.DefaultChannelId - -Dio.netty.processId: 1 (auto-detected)
api02-1  | 2025-08-18 06:24:03.917 [vert.x-eventloop-thread-1] DEBUG i.n.b.ChannelInitializerExtensions - -Dio.netty.bootstrap.extensions: null
api01-1  | 2025-08-18 06:24:03.984 [vert.x-eventloop-thread-1] DEBUG io.netty.channel.DefaultChannelId - -Dio.netty.machineId: e6:a7:4f:ff:fe:dd:47:fc (auto-detected)
api01-1  | 2025-08-18 06:24:03.998 [vert.x-eventloop-thread-1] DEBUG i.n.b.ChannelInitializerExtensions - -Dio.netty.bootstrap.extensions: null
api02-1  | 2025-08-18 06:24:03.999 [vert.x-eventloop-thread-1] INFO  b.c.r.paymentgateway.MainVerticle - HTTP server started on port 8080
api02-1  | 2025-08-18 06:24:04.000 [main] INFO  i.v.l.application.VertxApplication - Succeeded in deploying verticle
api01-1  | 2025-08-18 06:24:04.091 [vert.x-eventloop-thread-1] INFO  b.c.r.paymentgateway.MainVerticle - HTTP server started on port 8080
api01-1  | 2025-08-18 06:24:04.092 [main] INFO  i.v.l.application.VertxApplication - Succeeded in deploying verticle
api01-1  | 2025-08-18 06:24:04.790 [vert.x-eventloop-thread-1] DEBUG io.netty.buffer.AbstractByteBuf - -Dio.netty.buffer.checkAccessible: true
api01-1  | 2025-08-18 06:24:04.790 [vert.x-eventloop-thread-1] DEBUG io.netty.buffer.AbstractByteBuf - -Dio.netty.buffer.checkBounds: true
api01-1  | 2025-08-18 06:24:04.791 [vert.x-eventloop-thread-1] DEBUG i.n.util.ResourceLeakDetectorFactory - Loaded default ResourceLeakDetector: io.netty.util.ResourceLeakDetector@29cd5fa1
api01-1  | 2025-08-18 06:24:05.010 [vert.x-eventloop-thread-1] DEBUG i.n.h.c.compression.ZlibCodecFactory - -Dio.netty.noJdkZlibDecoder: false
api01-1  | 2025-08-18 06:24:05.011 [vert.x-eventloop-thread-1] DEBUG i.n.h.c.compression.ZlibCodecFactory - -Dio.netty.noJdkZlibEncoder: false
api01-1  | 2025-08-18 06:24:05.011 [vert.x-eventloop-thread-1] DEBUG i.n.h.c.compression.ZlibCodecFactory - JZlib not in the classpath; the only window bits supported value will be 15
api01-1  | 2025-08-18 06:24:05.393 [vert.x-eventloop-thread-1] DEBUG i.n.resolver.dns.DnsResolveContext - -Dio.netty.resolver.dns.tryCnameOnAddressLookups: false
api01-1  | 2025-08-18 06:24:05.395 [vert.x-eventloop-thread-1] DEBUG i.netty.resolver.dns.DnsQueryContext - -Dio.netty.resolver.dns.idReuseOnTimeoutDelayMillis: 10000
api01-1  | 2025-08-18 06:24:05.489 [vert.x-eventloop-thread-1] DEBUG i.n.util.ResourceLeakDetectorFactory - Loaded default ResourceLeakDetector: io.netty.util.ResourceLeakDetector@231a2388
api01-1  | 2025-08-18 06:24:05.586 [vert.x-eventloop-thread-1] DEBUG i.netty.resolver.dns.DnsQueryContext - [id: 0xcf4aca61, L:/[0:0:0:0:0:0:0:0]:42667] WRITE: UDP, [655: /127.0.0.11:53], DefaultDnsQuestion(db.ec2.internal. IN A)
api01-1  | 2025-08-18 06:24:05.593 [vert.x-eventloop-thread-1] DEBUG i.netty.resolver.dns.DnsNameResolver - [id: 0xcf4aca61, L:/[0:0:0:0:0:0:0:0]:42667] RECEIVED: UDP [655: /127.0.0.11:53], DatagramDnsResponse(from: /127.0.0.11:53, to: /[0:0:0:0:0:0:0:0]:42667, id: 655, QUERY(0), NXDomain(3), RD RA)
api01-1  | 	DefaultDnsQuestion(db.ec2.internal. IN A)
api01-1  | 	DefaultDnsRawRecord(ec2.internal. 60 IN SOA 49B)
api01-1  | 2025-08-18 06:24:05.683 [vert.x-eventloop-thread-1] DEBUG i.netty.resolver.dns.DnsQueryContext - [id: 0xcf4aca61, L:/[0:0:0:0:0:0:0:0]:42667] WRITE: UDP, [206: /127.0.0.11:53], DefaultDnsQuestion(db. IN A)
api01-1  | 2025-08-18 06:24:05.685 [vert.x-eventloop-thread-1] DEBUG i.netty.resolver.dns.DnsNameResolver - [id: 0xcf4aca61, L:/[0:0:0:0:0:0:0:0]:42667] RECEIVED: UDP [206: /127.0.0.11:53], DatagramDnsResponse(from: /127.0.0.11:53, to: /[0:0:0:0:0:0:0:0]:42667, id: 206, QUERY(0), NoError(0), RD RA)
api01-1  | 	DefaultDnsQuestion(db. IN A)
api01-1  | 	DefaultDnsRawRecord(db. 600 IN A 4B)
api01-1  | 2025-08-18 06:24:05.788 [vert.x-eventloop-thread-1] DEBUG i.v.p.i.a.scram.ScramAuthentication - Scram authentication is available com.ongres.scram.client.ScramClient$Builder@5c11692d
api01-1  | 2025-08-18 06:24:17.490 [vert.x-eventloop-thread-3] DEBUG i.netty.resolver.dns.DnsQueryContext - [id: 0x881a2be2, L:/[0:0:0:0:0:0:0:0]:44415] WRITE: UDP, [1935: /127.0.0.11:53], DefaultDnsQuestion(elb.ec2.internal. IN A)
api01-1  | 2025-08-18 06:24:17.493 [vert.x-eventloop-thread-3] DEBUG i.netty.resolver.dns.DnsNameResolver - [id: 0x881a2be2, L:/[0:0:0:0:0:0:0:0]:44415] RECEIVED: UDP [1935: /127.0.0.11:53], DatagramDnsResponse(from: /127.0.0.11:53, to: /[0:0:0:0:0:0:0:0]:44415, id: 1935, QUERY(0), NXDomain(3), RD RA)
api01-1  | 	DefaultDnsQuestion(elb.ec2.internal. IN A)
api01-1  | 	DefaultDnsRawRecord(ec2.internal. 60 IN SOA 49B)
api01-1  | 2025-08-18 06:24:17.493 [vert.x-eventloop-thread-3] DEBUG i.netty.resolver.dns.DnsQueryContext - [id: 0x881a2be2, L:/[0:0:0:0:0:0:0:0]:44415] WRITE: UDP, [4236: /127.0.0.11:53], DefaultDnsQuestion(elb. IN A)
api01-1  | 2025-08-18 06:24:17.494 [vert.x-eventloop-thread-3] DEBUG i.netty.resolver.dns.DnsNameResolver - [id: 0x881a2be2, L:/[0:0:0:0:0:0:0:0]:44415] RECEIVED: UDP [4236: /127.0.0.11:53], DatagramDnsResponse(from: /127.0.0.11:53, to: /[0:0:0:0:0:0:0:0]:44415, id: 4236, QUERY(0), NoError(0), RD RA)
api01-1  | 	DefaultDnsQuestion(elb. IN A)
api01-1  | 	DefaultDnsRawRecord(elb. 600 IN A 4B)
api02-1  | 2025-08-18 06:24:17.802 [vert.x-eventloop-thread-1] DEBUG io.netty.buffer.AbstractByteBuf - -Dio.netty.buffer.checkAccessible: true
api02-1  | 2025-08-18 06:24:17.802 [vert.x-eventloop-thread-1] DEBUG io.netty.buffer.AbstractByteBuf - -Dio.netty.buffer.checkBounds: true
api02-1  | 2025-08-18 06:24:17.804 [vert.x-eventloop-thread-1] DEBUG i.n.util.ResourceLeakDetectorFactory - Loaded default ResourceLeakDetector: io.netty.util.ResourceLeakDetector@79342050
api02-1  | 2025-08-18 06:24:17.929 [vert.x-eventloop-thread-1] DEBUG i.n.h.c.compression.ZlibCodecFactory - -Dio.netty.noJdkZlibDecoder: false
api02-1  | 2025-08-18 06:24:17.929 [vert.x-eventloop-thread-1] DEBUG i.n.h.c.compression.ZlibCodecFactory - -Dio.netty.noJdkZlibEncoder: false
api02-1  | 2025-08-18 06:24:17.929 [vert.x-eventloop-thread-1] DEBUG i.n.h.c.compression.ZlibCodecFactory - JZlib not in the classpath; the only window bits supported value will be 15
[Kapi01-1 exited with code 137
api02-1  | 2025-08-18 06:24:19.797 [vert.x-eventloop-thread-3] DEBUG i.n.resolver.dns.DnsResolveContext - -Dio.netty.resolver.dns.tryCnameOnAddressLookups: false
api02-1  | 2025-08-18 06:24:19.801 [vert.x-eventloop-thread-3] DEBUG i.netty.resolver.dns.DnsQueryContext - -Dio.netty.resolver.dns.idReuseOnTimeoutDelayMillis: 10000
api02-1  | 2025-08-18 06:24:19.897 [vert.x-eventloop-thread-3] DEBUG i.n.util.ResourceLeakDetectorFactory - Loaded default ResourceLeakDetector: io.netty.util.ResourceLeakDetector@2b8f5515
api02-1  | 2025-08-18 06:24:19.995 [vert.x-eventloop-thread-3] DEBUG i.netty.resolver.dns.DnsQueryContext - [id: 0x75155f04, L:/[0:0:0:0:0:0:0:0]:50459] WRITE: UDP, [15874: /127.0.0.11:53], DefaultDnsQuestion(elb.ec2.internal. IN A)
api02-1  | 2025-08-18 06:24:20.000 [vert.x-eventloop-thread-3] DEBUG i.netty.resolver.dns.DnsNameResolver - [id: 0x75155f04, L:/[0:0:0:0:0:0:0:0]:50459] RECEIVED: UDP [15874: /127.0.0.11:53], DatagramDnsResponse(from: /127.0.0.11:53, to: /[0:0:0:0:0:0:0:0]:50459, id: 15874, QUERY(0), NXDomain(3), RD RA)
api02-1  | 	DefaultDnsQuestion(elb.ec2.internal. IN A)
api02-1  | 	DefaultDnsRawRecord(ec2.internal. 60 IN SOA 49B)
api02-1  | 2025-08-18 06:24:20.001 [vert.x-eventloop-thread-3] DEBUG i.netty.resolver.dns.DnsQueryContext - [id: 0x75155f04, L:/[0:0:0:0:0:0:0:0]:50459] WRITE: UDP, [7856: /127.0.0.11:53], DefaultDnsQuestion(elb. IN A)
api02-1  | 2025-08-18 06:24:20.001 [vert.x-eventloop-thread-3] DEBUG i.netty.resolver.dns.DnsNameResolver - [id: 0x75155f04, L:/[0:0:0:0:0:0:0:0]:50459] RECEIVED: UDP [7856: /127.0.0.11:53], DatagramDnsResponse(from: /127.0.0.11:53, to: /[0:0:0:0:0:0:0:0]:50459, id: 7856, QUERY(0), NoError(0), RD RA)
api02-1  | 	DefaultDnsQuestion(elb. IN A)
api02-1  | 	DefaultDnsRawRecord(elb. 600 IN A 4B)
api02-1  | 2025-08-18 06:24:20.400 [vert.x-eventloop-thread-3] DEBUG i.netty.resolver.dns.DnsQueryContext - [id: 0x75155f04, L:/[0:0:0:0:0:0:0:0]:50459] WRITE: UDP, [9657: /127.0.0.11:53], DefaultDnsQuestion(db.ec2.internal. IN A)
api02-1  | 2025-08-18 06:24:20.500 [vert.x-eventloop-thread-3] DEBUG i.netty.resolver.dns.DnsNameResolver - [id: 0x75155f04, L:/[0:0:0:0:0:0:0:0]:50459] RECEIVED: UDP [9657: /127.0.0.11:53], DatagramDnsResponse(from: /127.0.0.11:53, to: /[0:0:0:0:0:0:0:0]:50459, id: 9657, QUERY(0), NXDomain(3), RD RA)
api02-1  | 	DefaultDnsQuestion(db.ec2.internal. IN A)
api02-1  | 	DefaultDnsRawRecord(ec2.internal. 60 IN SOA 49B)
api02-1  | 2025-08-18 06:24:20.501 [vert.x-eventloop-thread-3] DEBUG i.netty.resolver.dns.DnsQueryContext - [id: 0x75155f04, L:/[0:0:0:0:0:0:0:0]:50459] WRITE: UDP, [5135: /127.0.0.11:53], DefaultDnsQuestion(db. IN A)
api02-1  | 2025-08-18 06:24:20.504 [vert.x-eventloop-thread-3] DEBUG i.netty.resolver.dns.DnsNameResolver - [id: 0x75155f04, L:/[0:0:0:0:0:0:0:0]:50459] RECEIVED: UDP [5135: /127.0.0.11:53], DatagramDnsResponse(from: /127.0.0.11:53, to: /[0:0:0:0:0:0:0:0]:50459, id: 5135, QUERY(0), NoError(0), RD RA)
api02-1  | 	DefaultDnsQuestion(db. IN A)
api02-1  | 	DefaultDnsRawRecord(db. 600 IN A 4B)
api02-1  | 2025-08-18 06:24:20.698 [vert.x-eventloop-thread-3] DEBUG i.v.p.i.a.scram.ScramAuthentication - Scram authentication is available com.ongres.scram.client.ScramClient$Builder@5539ee06
db-1     | 2025-08-18 06:25:16.112 UTC [109] LOG:  could not receive data from client: Connection reset by peer
db-1     | 2025-08-18 06:25:16.113 UTC [108] LOG:  could not receive data from client: Connection reset by peer
db-1     | 2025-08-18 06:25:16.114 UTC [107] LOG:  could not receive data from client: Connection reset by peer
db-1     | 2025-08-18 06:25:16.117 UTC [104] LOG:  could not receive data from client: Connection reset by peer
[Kapi02-1 exited with code 137
elb-1    | [NOTICE]   (1) : haproxy version is 3.2.3-1844da7
elb-1    | [NOTICE]   (1) : path to executable is /usr/local/sbin/haproxy
elb-1    | [ALERT]    (1) : Current worker (8) exited with code 137 (Killed)
elb-1    | [WARNING]  (1) : A worker process unexpectedly died and this can only be explained by a bug in haproxy or its dependencies.
elb-1    | Please check that you are running an up to date and maintained version of haproxy and open a bug report.
elb-1    | [ALERT]    (1) : exit-on-failure: killing every processes with SIGTERM
elb-1    | [WARNING]  (1) : All workers exited. Exiting... (137)
elb-1    | HAProxy version 3.2.3-1844da7 2025/07/09 - https://haproxy.org/
elb-1    | Status: long-term supported branch - will stop receiving fixes around Q2 2030.
elb-1    | Known bugs: http://www.haproxy.org/bugs/bugs-3.2.3.html
elb-1    | Running on: Linux 6.14.0-1010-aws #10~24.04.1-Ubuntu SMP Fri Jul 18 20:44:30 UTC 2025 x86_64
[Kelb-1 exited with code 137
elb-1    | [NOTICE]   (1) : Initializing new worker (8)
elb-1    | [NOTICE]   (8) : haproxy version is 3.2.3-1844da7
elb-1    | [NOTICE]   (8) : path to executable is /usr/local/sbin/haproxy
elb-1    | [ALERT]    (8) : [/usr/local/etc/haproxy/haproxy.cfg:27] : 'server payment/s1' : could not resolve address 'api01'.
elb-1    | [ALERT]    (8) : [/usr/local/etc/haproxy/haproxy.cfg:28] : 'server payment/s2' : could not resolve address 'api02'.
elb-1    | [ALERT]    (8) : [/usr/local/etc/haproxy/haproxy.cfg:35] : 'server summary/s1' : could not resolve address 'api01'.
elb-1    | [ALERT]    (8) : [/usr/local/etc/haproxy/haproxy.cfg:36] : 'server summary/s2' : could not resolve address 'api02'.
elb-1    | [ALERT]    (8) : Failed to initialize server(s) addr.
elb-1    | [NOTICE]   (1) : haproxy version is 3.2.3-1844da7
elb-1    | [NOTICE]   (1) : path to executable is /usr/local/sbin/haproxy
elb-1    | [WARNING]  (1) : Failed to load worker!
[Kelb-1 exited with code 1
elb-1    | [NOTICE]   (1) : Initializing new worker (8)
elb-1    | [NOTICE]   (8) : haproxy version is 3.2.3-1844da7
elb-1    | [NOTICE]   (8) : path to executable is /usr/local/sbin/haproxy
elb-1    | [ALERT]    (8) : [/usr/local/etc/haproxy/haproxy.cfg:27] : 'server payment/s1' : could not resolve address 'api01'.
elb-1    | [ALERT]    (8) : [/usr/local/etc/haproxy/haproxy.cfg:28] : 'server payment/s2' : could not resolve address 'api02'.
elb-1    | [ALERT]    (8) : [/usr/local/etc/haproxy/haproxy.cfg:35] : 'server summary/s1' : could not resolve address 'api01'.
elb-1    | [ALERT]    (8) : [/usr/local/etc/haproxy/haproxy.cfg:36] : 'server summary/s2' : could not resolve address 'api02'.
elb-1    | [ALERT]    (8) : Failed to initialize server(s) addr.
elb-1    | [NOTICE]   (1) : haproxy version is 3.2.3-1844da7
elb-1    | [NOTICE]   (1) : path to executable is /usr/local/sbin/haproxy
elb-1    | [WARNING]  (1) : Failed to load worker!
[Kelb-1 exited with code 1
elb-1    | [NOTICE]   (1) : Initializing new worker (8)
elb-1    | [NOTICE]   (8) : haproxy version is 3.2.3-1844da7
elb-1    | [NOTICE]   (8) : path to executable is /usr/local/sbin/haproxy
elb-1    | [ALERT]    (8) : [/usr/local/etc/haproxy/haproxy.cfg:27] : 'server payment/s1' : could not resolve address 'api01'.
elb-1    | [ALERT]    (8) : [/usr/local/etc/haproxy/haproxy.cfg:28] : 'server payment/s2' : could not resolve address 'api02'.
elb-1    | [ALERT]    (8) : [/usr/local/etc/haproxy/haproxy.cfg:35] : 'server summary/s1' : could not resolve address 'api01'.
elb-1    | [ALERT]    (8) : [/usr/local/etc/haproxy/haproxy.cfg:36] : 'server summary/s2' : could not resolve address 'api02'.
elb-1    | [ALERT]    (8) : Failed to initialize server(s) addr.
elb-1    | [NOTICE]   (1) : haproxy version is 3.2.3-1844da7
elb-1    | [NOTICE]   (1) : path to executable is /usr/local/sbin/haproxy
elb-1    | [WARNING]  (1) : Failed to load worker!
[Kelb-1 exited with code 1
elb-1    | [NOTICE]   (1) : Initializing new worker (8)
elb-1    | [NOTICE]   (8) : haproxy version is 3.2.3-1844da7
elb-1    | [NOTICE]   (8) : path to executable is /usr/local/sbin/haproxy
elb-1    | [ALERT]    (8) : [/usr/local/etc/haproxy/haproxy.cfg:27] : 'server payment/s1' : could not resolve address 'api01'.
elb-1    | [ALERT]    (8) : [/usr/local/etc/haproxy/haproxy.cfg:28] : 'server payment/s2' : could not resolve address 'api02'.
elb-1    | [ALERT]    (8) : [/usr/local/etc/haproxy/haproxy.cfg:35] : 'server summary/s1' : could not resolve address 'api01'.
elb-1    | [ALERT]    (8) : [/usr/local/etc/haproxy/haproxy.cfg:36] : 'server summary/s2' : could not resolve address 'api02'.
elb-1    | [ALERT]    (8) : Failed to initialize server(s) addr.
elb-1    | [NOTICE]   (1) : haproxy version is 3.2.3-1844da7
elb-1    | [NOTICE]   (1) : path to executable is /usr/local/sbin/haproxy
elb-1    | [WARNING]  (1) : Failed to load worker!
[Kelb-1 exited with code 1
elb-1    | [NOTICE]   (1) : Initializing new worker (8)
elb-1    | [NOTICE]   (8) : haproxy version is 3.2.3-1844da7
elb-1    | [NOTICE]   (8) : path to executable is /usr/local/sbin/haproxy
elb-1    | [ALERT]    (8) : [/usr/local/etc/haproxy/haproxy.cfg:27] : 'server payment/s1' : could not resolve address 'api01'.
elb-1    | [ALERT]    (8) : [/usr/local/etc/haproxy/haproxy.cfg:28] : 'server payment/s2' : could not resolve address 'api02'.
elb-1    | [ALERT]    (8) : [/usr/local/etc/haproxy/haproxy.cfg:35] : 'server summary/s1' : could not resolve address 'api01'.
elb-1    | [ALERT]    (8) : [/usr/local/etc/haproxy/haproxy.cfg:36] : 'server summary/s2' : could not resolve address 'api02'.
elb-1    | [ALERT]    (8) : Failed to initialize server(s) addr.
elb-1    | [NOTICE]   (1) : haproxy version is 3.2.3-1844da7
elb-1    | [NOTICE]   (1) : path to executable is /usr/local/sbin/haproxy
elb-1    | [WARNING]  (1) : Failed to load worker!
[Kelb-1 exited with code 1
elb-1    | [NOTICE]   (1) : Initializing new worker (8)
elb-1    | [NOTICE]   (8) : haproxy version is 3.2.3-1844da7
elb-1    | [NOTICE]   (8) : path to executable is /usr/local/sbin/haproxy
elb-1    | [ALERT]    (8) : [/usr/local/etc/haproxy/haproxy.cfg:27] : 'server payment/s1' : could not resolve address 'api01'.
elb-1    | [ALERT]    (8) : [/usr/local/etc/haproxy/haproxy.cfg:28] : 'server payment/s2' : could not resolve address 'api02'.
elb-1    | [ALERT]    (8) : [/usr/local/etc/haproxy/haproxy.cfg:35] : 'server summary/s1' : could not resolve address 'api01'.
elb-1    | [ALERT]    (8) : [/usr/local/etc/haproxy/haproxy.cfg:36] : 'server summary/s2' : could not resolve address 'api02'.
elb-1    | [ALERT]    (8) : Failed to initialize server(s) addr.
elb-1    | [NOTICE]   (1) : haproxy version is 3.2.3-1844da7
elb-1    | [NOTICE]   (1) : path to executable is /usr/local/sbin/haproxy
elb-1    | [WARNING]  (1) : Failed to load worker!
[Kelb-1 exited with code 1
elb-1    | [NOTICE]   (1) : Initializing new worker (8)
elb-1    | [NOTICE]   (8) : haproxy version is 3.2.3-1844da7
elb-1    | [NOTICE]   (8) : path to executable is /usr/local/sbin/haproxy
elb-1    | [ALERT]    (8) : [/usr/local/etc/haproxy/haproxy.cfg:27] : 'server payment/s1' : could not resolve address 'api01'.
elb-1    | [ALERT]    (8) : [/usr/local/etc/haproxy/haproxy.cfg:28] : 'server payment/s2' : could not resolve address 'api02'.
elb-1    | [ALERT]    (8) : [/usr/local/etc/haproxy/haproxy.cfg:35] : 'server summary/s1' : could not resolve address 'api01'.
elb-1    | [ALERT]    (8) : [/usr/local/etc/haproxy/haproxy.cfg:36] : 'server summary/s2' : could not resolve address 'api02'.
elb-1    | [ALERT]    (8) : Failed to initialize server(s) addr.
elb-1    | [NOTICE]   (1) : haproxy version is 3.2.3-1844da7
elb-1    | [NOTICE]   (1) : path to executable is /usr/local/sbin/haproxy
elb-1    | [WARNING]  (1) : Failed to load worker!
[Kelb-1 exited with code 1
elb-1    | [NOTICE]   (1) : Initializing new worker (8)
elb-1    | [NOTICE]   (8) : haproxy version is 3.2.3-1844da7
elb-1    | [NOTICE]   (8) : path to executable is /usr/local/sbin/haproxy
elb-1    | [ALERT]    (8) : [/usr/local/etc/haproxy/haproxy.cfg:27] : 'server payment/s1' : could not resolve address 'api01'.
elb-1    | [ALERT]    (8) : [/usr/local/etc/haproxy/haproxy.cfg:28] : 'server payment/s2' : could not resolve address 'api02'.
elb-1    | [ALERT]    (8) : [/usr/local/etc/haproxy/haproxy.cfg:35] : 'server summary/s1' : could not resolve address 'api01'.
elb-1    | [ALERT]    (8) : [/usr/local/etc/haproxy/haproxy.cfg:36] : 'server summary/s2' : could not resolve address 'api02'.
elb-1    | [ALERT]    (8) : Failed to initialize server(s) addr.
elb-1    | [NOTICE]   (1) : haproxy version is 3.2.3-1844da7
elb-1    | [NOTICE]   (1) : path to executable is /usr/local/sbin/haproxy
elb-1    | [WARNING]  (1) : Failed to load worker!
[Kelb-1 exited with code 1
elb-1    | [NOTICE]   (1) : Initializing new worker (8)
elb-1    | [NOTICE]   (8) : haproxy version is 3.2.3-1844da7
elb-1    | [NOTICE]   (8) : path to executable is /usr/local/sbin/haproxy
elb-1    | [ALERT]    (8) : [/usr/local/etc/haproxy/haproxy.cfg:27] : 'server payment/s1' : could not resolve address 'api01'.
elb-1    | [ALERT]    (8) : [/usr/local/etc/haproxy/haproxy.cfg:28] : 'server payment/s2' : could not resolve address 'api02'.
elb-1    | [ALERT]    (8) : [/usr/local/etc/haproxy/haproxy.cfg:35] : 'server summary/s1' : could not resolve address 'api01'.
elb-1    | [ALERT]    (8) : [/usr/local/etc/haproxy/haproxy.cfg:36] : 'server summary/s2' : could not resolve address 'api02'.
elb-1    | [ALERT]    (8) : Failed to initialize server(s) addr.
elb-1    | [NOTICE]   (1) : haproxy version is 3.2.3-1844da7
elb-1    | [NOTICE]   (1) : path to executable is /usr/local/sbin/haproxy
elb-1    | [WARNING]  (1) : Failed to load worker!
[Kelb-1 exited with code 1
elb-1    | [NOTICE]   (1) : Initializing new worker (8)
elb-1    | [NOTICE]   (8) : haproxy version is 3.2.3-1844da7
elb-1    | [NOTICE]   (8) : path to executable is /usr/local/sbin/haproxy
elb-1    | [ALERT]    (8) : [/usr/local/etc/haproxy/haproxy.cfg:27] : 'server payment/s1' : could not resolve address 'api01'.
elb-1    | [ALERT]    (8) : [/usr/local/etc/haproxy/haproxy.cfg:28] : 'server payment/s2' : could not resolve address 'api02'.
elb-1    | [ALERT]    (8) : [/usr/local/etc/haproxy/haproxy.cfg:35] : 'server summary/s1' : could not resolve address 'api01'.
elb-1    | [ALERT]    (8) : [/usr/local/etc/haproxy/haproxy.cfg:36] : 'server summary/s2' : could not resolve address 'api02'.
elb-1    | [ALERT]    (8) : Failed to initialize server(s) addr.
elb-1    | [NOTICE]   (1) : haproxy version is 3.2.3-1844da7
elb-1    | [NOTICE]   (1) : path to executable is /usr/local/sbin/haproxy
elb-1    | [WARNING]  (1) : Failed to load worker!
[Kelb-1 exited with code 1
db-1     | 2025-08-18 06:29:25.011 UTC [1] LOG:  received fast shutdown request
db-1     | 2025-08-18 06:29:25.011 UTC [1] LOG:  aborting any active transactions
db-1     | 2025-08-18 06:29:25.013 UTC [1] LOG:  background worker "logical replication launcher" (PID 69) exited with exit code 1
db-1     | 2025-08-18 06:29:25.014 UTC [64] LOG:  shutting down
db-1     | 2025-08-18 06:29:25.014 UTC [64] LOG:  checkpoint starting: shutdown immediate
db-1     | 2025-08-18 06:29:25.015 UTC [64] LOG:  checkpoint complete: wrote 70 buffers (0.4%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.001 s, sync=0.001 s, total=0.002 s; sync files=0, longest=0.000 s, average=0.000 s; distance=273 kB, estimate=273 kB; lsn=0/19653A0, redo lsn=0/19653A0
db-1     | 2025-08-18 06:29:25.021 UTC [1] LOG:  database system is shut down
log truncated at line 1000
